### ISSUE TITLE
pcas ?

### ISSUE THREAD

**Issue by drupol** [ec-europa/eu-login-phpcas-wrapper#1]
Hi,

You could also use the [pcas](https://github.com/drupol/pcas) library, it already has all the functionalities for login/logout and more.

Let me know if you need some help.

**Comment by scriptsagency** [comment]
Hi Pol, 

I opened this discussion inside the team and the decision is to use phpCAS 
Your library looks good and could be a solution for the future once it will become mature. 

Thanks for the recommendation

**Comment by drupol** [comment]
Hi, 

Could you please elaborate and describe a bit more what you mean by mature? 
In other words, what prevent you from using it over phpcas? 

Thanks.

**Comment by gboddin** [comment]
@scriptsagency please note you're also redoing https://github.com/ec-europa/ecas-phpcas-parser

I can for instance tell you that your implementation doesn't support groups.

BTW Post validation parsing callback is a feature we developed for phpCAS and which was integrated to master a few months ago so we could parse ecas's custom response ( https://github.com/apereo/phpCAS/pull/205 ). 

If you really want to use PHPCAS, the mentionned library is tested and working in multiple CMS/environments.

4 libs is just too much, I'll have to make this repo read-only, sorry.

**Comment by scriptsagency** [comment]
@drupol 
The update is intended for webtools which is already using phpCas 
The version needs to be updated to the latest one and the option for assurance level to be passed to service/proxy validator 
Changing the library is a different project which is out of the current story scope . 
Also my reply is not related to the dashboard project which is a different topic .

**Comment by drupol** [comment]
Thanks for the clarification :+1: 

Feel free to ping me if you'd like to use pcas anytime soon.

**Comment by scriptsagency** [comment]
@gboddin 
I've added the parser implemented in your libray : https://github.com/ec-europa/ecas-phpcas-parser
Thanks for the feedback. 

Since this is read only I can't update the repo, but now it should support group parsing .

**Comment by drupol** [comment]
So sad that we have to do the work twice... this parsing is by default in pcas.
![screenshot-2018-4-4 pcas a php cas library](https://user-images.githubusercontent.com/252042/38312733-c5768306-3822-11e8-8f94-10f8bbe537a8.png)
